import {
  X,
  Sparkles,
  TrendingUp,
  AlertCircle,
  CheckCircle,
  Lightbulb,
} from "lucide-react";
import { useEffect, useMemo, useRef } from "react";
import { useLanguage } from "../contexts/LanguageContext";

// ─── i18n helper ─────────────────────────────────────────────────────────
const TR = {
  title: "AI Analiz Raporu",
  hive: "Kovan",
  healthScore: "Genel Sağlık Skoru",
  excellent: "Mükemmel",
  good: "İyi",
  poor: "Zayıf",
  healthExcellentDesc: "Koloni sağlığı mükemmel durumda",
  healthGoodDesc: "Koloni sağlığı iyi, izleme gerekli",
  healthPoorDesc: "Acil müdahale gerekli",
  predictions: "AI Tahminleri",
  actions: "Önerilen Aksiyonlar",
  note: "Not",
  disclaimer:
    "Bu analiz AI modeli tarafından oluşturulmuştur. Kesin teşhis için deneyimli bir arıcıya danışmanız önerilir.",
  riskHigh: "Yüksek Risk",
  riskMedium: "Orta Risk",
  riskLow: "Düşük Risk",
  probability: "Olasılık",
  estProduction: "Tahmini Üretim",
  swarm: "Oğul Riski",
  varroa: "Varroa Riski",
  production: "Bal Üretimi",
  health: "Koloni Sağlığı",
  close: "Kapat",
  week: "hafta",
  // timeframes
  swarmHighTf: "1-3 gün içinde",
  swarmMedTf: "5-10 gün içinde",
  swarmLowTf: "Düşük risk",
  varroaMethod: "Ses frekans analizine göre",
  // recommendations
  swarmHighRec:
    "Acil oğul kontrolü yapın. Ana arı hücrelerini inceleyin. Çerçeve ekleyin.",
  swarmMedRec: "Yakın takip edin. 2-3 günde bir kontrol edin.",
  swarmLowRec: "Normal izleme yeterli.",
  varroaHighRec: "Varroa tedavisi başlatın. Oksalik asit veya timol uygulayın.",
  varroaMedRec: "Varroa sayımı yapın. Eşik aşılmışsa tedavi başlatın.",
  varroaLowRec: "Varroa riski düşük. Aylık kontrol yeterli.",
  prodUpRec: "Bal üretimi iyi. 2 hafta içinde hasat planlanabilir.",
  prodStableRec: "Üretim normal. Beslenme desteği verilebilir.",
  prodDownRec: "Üretim düşük. Koloni sağlığını öncelikli kontrol edin.",
  healthGoodRec: "Koloni sağlıklı. Rutin bakım yeterli.",
  healthModRec: "Dikkat gerektiren parametreler var. Yakın takip edin.",
  healthPoorRec: "Koloni risk altında. Acil müdahale gerekli.",
  // actions
  actVentilate: "Havalandırmayı artırın, gölgeleme yapın",
  actInsulate: "Kovanı izole edin, yalıtım ekleyin",
  actDehumidify: "Nem giderici ekleyin, havalandırma açın",
  actHumidify: "Su kaynağı ekleyin, nemlendiriciden faydalanın",
  actSwarmCheck: "Oğul kontrolü yapın, ana arıyı kontrol edin",
  actVarroaTest: "Varroa testi yapın (şeker tozu veya alkol yıkama)",
  actBattery: "Sensör pilini değiştirin",
  actRoutine: "Haftalık rutin kontrole devam edin",
  // issues
  issueTempCrit: (v) => `Kritik sıcaklık: ${v}°C (>40°C)`,
  issueTempHigh: (v) => `Yüksek sıcaklık: ${v}°C`,
  issueTempVeryLow: (v) => `Çok düşük sıcaklık: ${v}°C (<10°C)`,
  issueTempLow: (v) => `Düşük sıcaklık: ${v}°C`,
  issueHumExcess: (v) => `Aşırı nem: %${v} (>85%)`,
  issueHumHigh: (v) => `Yüksek nem: %${v}`,
  issueHumVeryLow: (v) => `Çok düşük nem: %${v} (<30%)`,
  issueSound: (v) => `Anormal ses seviyesi: ${v} dB`,
  issueVib: (v) => `Yüksek titreşim: ${v}`,
  issueBattery: (v) => `Pil kritik: %${v}`,
};

const EN = {
  title: "AI Analysis Report",
  hive: "Hive",
  healthScore: "Overall Health Score",
  excellent: "Excellent",
  good: "Good",
  poor: "Poor",
  healthExcellentDesc: "Colony health is excellent",
  healthGoodDesc: "Colony health is good, monitoring needed",
  healthPoorDesc: "Urgent intervention needed",
  predictions: "AI Predictions",
  actions: "Recommended Actions",
  note: "Note",
  disclaimer:
    "This analysis was generated by an AI model. For definitive diagnosis, consulting an experienced beekeeper is recommended.",
  riskHigh: "High Risk",
  riskMedium: "Medium Risk",
  riskLow: "Low Risk",
  probability: "Probability",
  estProduction: "Est. Production",
  swarm: "Swarm Risk",
  varroa: "Varroa Risk",
  production: "Honey Production",
  health: "Colony Health",
  close: "Close",
  week: "week",
  swarmHighTf: "within 1-3 days",
  swarmMedTf: "within 5-10 days",
  swarmLowTf: "Low risk",
  varroaMethod: "Based on sound frequency analysis",
  swarmHighRec: "Urgent swarm check. Inspect queen cells. Add frames.",
  swarmMedRec: "Monitor closely. Check every 2-3 days.",
  swarmLowRec: "Normal monitoring is sufficient.",
  varroaHighRec: "Start Varroa treatment. Apply oxalic acid or thymol.",
  varroaMedRec: "Perform Varroa count. Start treatment if threshold exceeded.",
  varroaLowRec: "Varroa risk is low. Monthly check is sufficient.",
  prodUpRec: "Honey production is good. Harvest can be planned in 2 weeks.",
  prodStableRec: "Production is normal. Feeding support can be given.",
  prodDownRec: "Production is low. Prioritize colony health check.",
  healthGoodRec: "Colony is healthy. Routine care is sufficient.",
  healthModRec: "Some parameters need attention. Monitor closely.",
  healthPoorRec: "Colony is at risk. Urgent intervention needed.",
  actVentilate: "Increase ventilation, add shading",
  actInsulate: "Insulate the hive, add insulation",
  actDehumidify: "Add dehumidifier, open ventilation",
  actHumidify: "Add water source, use humidifier",
  actSwarmCheck: "Check for swarming, inspect queen bee",
  actVarroaTest: "Perform Varroa test (sugar shake or alcohol wash)",
  actBattery: "Replace sensor battery",
  actRoutine: "Continue weekly routine inspections",
  issueTempCrit: (v) => `Critical temperature: ${v}°C (>40°C)`,
  issueTempHigh: (v) => `High temperature: ${v}°C`,
  issueTempVeryLow: (v) => `Very low temperature: ${v}°C (<10°C)`,
  issueTempLow: (v) => `Low temperature: ${v}°C`,
  issueHumExcess: (v) => `Excessive humidity: ${v}% (>85%)`,
  issueHumHigh: (v) => `High humidity: ${v}%`,
  issueHumVeryLow: (v) => `Very low humidity: ${v}% (<30%)`,
  issueSound: (v) => `Abnormal sound level: ${v} dB`,
  issueVib: (v) => `High vibration: ${v}`,
  issueBattery: (v) => `Battery critical: ${v}%`,
};

// ─── Component ───────────────────────────────────────────────────────────
const AIAnalysisPanel = ({ isOpen, onClose, hive }) => {
  const { lang } = useLanguage();
  const t = lang === "tr" ? TR : EN;
  const closeBtnRef = useRef(null);

  // ESC to close + scroll lock + initial focus
  useEffect(() => {
    if (!isOpen) return;

    const handleKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handleKey);

    const originalOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    // focus close button for accessibility
    closeBtnRef.current?.focus();

    return () => {
      document.removeEventListener("keydown", handleKey);
      document.body.style.overflow = originalOverflow;
    };
  }, [isOpen, onClose]);

  // Memoize analysis so it doesn't recompute on every render
  const analysis = useMemo(
    () => (hive ? analyzeHive(hive, t) : null),
    [hive, t],
  );

  if (!isOpen || !hive || !analysis) return null;

  const healthColor = getHealthColor(analysis.healthScore);
  const healthLabel =
    analysis.healthScore >= 80
      ? t.excellent
      : analysis.healthScore >= 60
        ? t.good
        : t.poor;
  const healthDesc =
    analysis.healthScore >= 80
      ? t.healthExcellentDesc
      : analysis.healthScore >= 60
        ? t.healthGoodDesc
        : t.healthPoorDesc;

  const handleBackdropClick = (e) => {
    if (e.target === e.currentTarget) onClose();
  };

  return (
    <div
      className="fixed inset-0 bg-black/70 backdrop-blur-sm z-[100] flex items-center justify-center p-4 animate-fade-in"
      onClick={handleBackdropClick}
      role="dialog"
      aria-modal="true"
      aria-labelledby="ai-analysis-title"
    >
      <div className="bg-gray-900 border border-gray-700 rounded-lg max-w-3xl w-full max-h-[90vh] overflow-hidden shadow-2xl animate-scale-in">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-800 bg-gradient-to-r from-purple-500/10 to-pink-500/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-purple-500/20 rounded-full flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-purple-400" />
            </div>
            <div>
              <h3
                id="ai-analysis-title"
                className="text-lg font-semibold text-gray-100"
              >
                {t.title}
              </h3>
              <p className="text-sm text-gray-500">
                {t.hive} #{hive.id ?? "—"}
              </p>
            </div>
          </div>
          <button
            ref={closeBtnRef}
            onClick={onClose}
            aria-label={t.close}
            className="p-2 hover:bg-gray-800 rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-purple-500"
          >
            <X className="w-5 h-5 text-gray-400" />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-80px)] custom-scroll">
          {/* Health Score */}
          <section className="mb-6">
            <h4 className="text-sm font-semibold text-gray-400 uppercase mb-3">
              {t.healthScore}
            </h4>
            <div className="flex items-center gap-4">
              <HealthRing
                score={analysis.healthScore}
                colorClass={healthColor.text}
              />
              <div>
                <p className="text-2xl font-bold text-gray-100 mb-1">
                  {healthLabel}
                </p>
                <p className="text-sm text-gray-500">{healthDesc}</p>
              </div>
            </div>
          </section>

          {/* Predictions */}
          <section className="mb-6">
            <h4 className="text-sm font-semibold text-gray-400 uppercase mb-3 flex items-center gap-2">
              <TrendingUp className="w-4 h-4" />
              {t.predictions}
            </h4>
            <div className="space-y-3">
              {analysis.predictions.map((pred, i) => (
                <PredictionCard key={`${pred.type}-${i}`} pred={pred} t={t} />
              ))}
            </div>
          </section>

          {/* Actions */}
          <section>
            <h4 className="text-sm font-semibold text-gray-400 uppercase mb-3 flex items-center gap-2">
              <CheckCircle className="w-4 h-4" />
              {t.actions}
            </h4>
            <div className="bg-gray-800 rounded-lg p-4">
              <ul className="space-y-2">
                {analysis.actions.map((action, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-3 text-sm text-gray-300"
                  >
                    <span
                      className="text-amber-400 font-semibold"
                      aria-hidden="true"
                    >
                      {i + 1}.
                    </span>
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* Disclaimer */}
          <div className="mt-6 p-4 bg-blue-500/10 border border-blue-500/30 rounded-lg">
            <p className="text-xs text-gray-400">
              💡 <strong>{t.note}:</strong> {t.disclaimer}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

// ─── Subcomponents ───────────────────────────────────────────────────────
const HealthRing = ({ score, colorClass }) => {
  const RADIUS = 40;
  const CIRCUMFERENCE = 2 * Math.PI * RADIUS;
  const offset = CIRCUMFERENCE * (1 - score / 100);

  return (
    <div
      className="relative w-24 h-24"
      role="img"
      aria-label={`Health score ${score}`}
    >
      <svg className="transform -rotate-90 w-24 h-24">
        <circle
          cx="48"
          cy="48"
          r={RADIUS}
          stroke="currentColor"
          strokeWidth="8"
          fill="none"
          className="text-gray-800"
        />
        <circle
          cx="48"
          cy="48"
          r={RADIUS}
          stroke="currentColor"
          strokeWidth="8"
          fill="none"
          strokeDasharray={CIRCUMFERENCE}
          strokeDashoffset={offset}
          className={`${colorClass} transition-[stroke-dashoffset] duration-700`}
          strokeLinecap="round"
        />
      </svg>
      <div className="absolute inset-0 flex items-center justify-center">
        <span className="text-2xl font-bold text-gray-100">{score}</span>
      </div>
    </div>
  );
};

const PredictionCard = ({ pred, t }) => {
  const riskLabels = { high: t.riskHigh, medium: t.riskMedium, low: t.riskLow };
  const riskColors = {
    high: "text-red-400",
    medium: "text-amber-400",
    low: "text-emerald-400",
  };
  const typeLabels = {
    swarm: t.swarm,
    varroa: t.varroa,
    production: t.production,
    health: t.health,
  };

  return (
    <div className="bg-gray-800 rounded-lg p-4">
      <div className="flex items-start justify-between mb-2 gap-2">
        <h5 className="font-semibold text-gray-100">{typeLabels[pred.type]}</h5>
        {pred.risk && (
          <span
            className={`text-xs font-semibold uppercase whitespace-nowrap ${riskColors[pred.risk]}`}
          >
            {riskLabels[pred.risk]}
          </span>
        )}
      </div>

      {pred.probability && (
        <p className="text-sm text-gray-400 mb-1">
          {t.probability}:{" "}
          <span className="font-semibold text-gray-300">
            {pred.probability}
          </span>
          {pred.timeframe && <> ({pred.timeframe})</>}
        </p>
      )}

      {pred.value && (
        <p className="text-sm text-gray-400 mb-1">
          {t.estProduction}:{" "}
          <span className="font-semibold text-gray-300">{pred.value}</span>
        </p>
      )}

      {pred.issues?.length > 0 && (
        <div className="mt-2 space-y-1">
          {pred.issues.map((issue, j) => (
            <div
              key={j}
              className="flex items-center gap-2 text-sm text-red-400"
            >
              <AlertCircle className="w-3 h-3 flex-shrink-0" />
              <span>{issue}</span>
            </div>
          ))}
        </div>
      )}

      <p className="text-sm text-purple-400 mt-2 flex items-start gap-2">
        <Lightbulb className="w-4 h-4 flex-shrink-0 mt-0.5" />
        <span>{pred.recommendation}</span>
      </p>
    </div>
  );
};

// ─── Helpers ─────────────────────────────────────────────────────────────
const getHealthColor = (score) => {
  if (score >= 80) return { bg: "bg-emerald-500", text: "text-emerald-400" };
  if (score >= 60) return { bg: "bg-amber-500", text: "text-amber-400" };
  return { bg: "bg-red-500", text: "text-red-400" };
};

const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
const sum = (arr) => arr.reduce((a, b) => a + b, 0);

export default AIAnalysisPanel;

// ═══════════════════════════════════════════════════════════════════════════
//  RULE-BASED AI ANALYSIS ENGINE
// ═══════════════════════════════════════════════════════════════════════════
function analyzeHive(hive, t) {
  const temp = Number(hive.temp) || 0;
  const humidity = Number(hive.humidity) || 0;
  const sound = Number(hive.sound) || 0;
  const vibration = Number(hive.vibration) || 0;
  const battery = hive.battery ?? 100;

  const issues = [];
  let healthScore = 100;

  // Temperature
  if (temp > 40) {
    healthScore -= 30;
    issues.push(t.issueTempCrit(temp));
  } else if (temp > 37) {
    healthScore -= 15;
    issues.push(t.issueTempHigh(temp));
  } else if (temp < 10) {
    healthScore -= 25;
    issues.push(t.issueTempVeryLow(temp));
  } else if (temp < 20) {
    healthScore -= 10;
    issues.push(t.issueTempLow(temp));
  }

  // Humidity
  if (humidity > 85) {
    healthScore -= 20;
    issues.push(t.issueHumExcess(humidity));
  } else if (humidity > 75) {
    healthScore -= 10;
    issues.push(t.issueHumHigh(humidity));
  } else if (humidity < 30) {
    healthScore -= 15;
    issues.push(t.issueHumVeryLow(humidity));
  }

  // Sound
  if (sound > 80) {
    healthScore -= 20;
    issues.push(t.issueSound(sound));
  } else if (sound > 60) {
    healthScore -= 8;
  }

  // Vibration
  if (vibration > 2000) {
    healthScore -= 20;
    issues.push(t.issueVib(vibration));
  } else if (vibration > 1000) {
    healthScore -= 10;
  }

  // Battery
  if (battery < 15) {
    healthScore -= 5;
    issues.push(t.issueBattery(battery));
  }

  healthScore = clamp(healthScore, 0, 100);

  // Swarm probability
  const swarmFactors = [];
  if (temp > 40) swarmFactors.push(0.5);
  else if (temp > 36) swarmFactors.push(0.3);
  if (humidity > 70) swarmFactors.push(0.2);
  if (sound > 65) swarmFactors.push(0.35);
  if (vibration > 1200) swarmFactors.push(0.25);
  const swarmProb = Math.min(0.95, sum(swarmFactors));
  const swarmRisk =
    swarmProb > 0.6 ? "high" : swarmProb > 0.3 ? "medium" : "low";

  // Varroa probability
  const varroaFactors = [];
  if (sound > 55 && sound < 75) varroaFactors.push(0.25);
  if (temp > 35 && humidity > 65) varroaFactors.push(0.2);
  if (vibration > 800 && vibration < 1500) varroaFactors.push(0.15);
  const varroaProb = Math.min(0.9, sum(varroaFactors));
  const varroaRisk =
    varroaProb > 0.5 ? "high" : varroaProb > 0.2 ? "medium" : "low";

  // Actions (deduplicated via Set)
  const actionSet = new Set();
  if (temp > 38) actionSet.add(t.actVentilate);
  if (temp < 15) actionSet.add(t.actInsulate);
  if (humidity > 80) actionSet.add(t.actDehumidify);
  if (humidity < 35) actionSet.add(t.actHumidify);
  if (swarmRisk === "high") actionSet.add(t.actSwarmCheck);
  if (varroaRisk !== "low") actionSet.add(t.actVarroaTest);
  if (battery < 20) actionSet.add(t.actBattery);
  if (actionSet.size === 0) actionSet.add(t.actRoutine);
  const actions = Array.from(actionSet);

  // Production estimate
  const prodFactor = healthScore > 80 ? 1.0 : healthScore > 60 ? 0.7 : 0.3;
  const weeklyProd = (3.0 * prodFactor).toFixed(1);
  const prodTrend =
    healthScore > 80 ? "up" : healthScore > 60 ? "stable" : "down";

  return {
    healthScore,
    predictions: [
      {
        type: "swarm",
        risk: swarmRisk,
        probability: `${Math.round(swarmProb * 100)}%`,
        timeframe:
          swarmRisk === "high"
            ? t.swarmHighTf
            : swarmRisk === "medium"
              ? t.swarmMedTf
              : t.swarmLowTf,
        recommendation:
          swarmRisk === "high"
            ? t.swarmHighRec
            : swarmRisk === "medium"
              ? t.swarmMedRec
              : t.swarmLowRec,
      },
      {
        type: "varroa",
        risk: varroaRisk,
        probability: `${Math.round(varroaProb * 100)}%`,
        timeframe: t.varroaMethod,
        recommendation:
          varroaRisk === "high"
            ? t.varroaHighRec
            : varroaRisk === "medium"
              ? t.varroaMedRec
              : t.varroaLowRec,
      },
      {
        type: "production",
        value: `${weeklyProd} kg/${t.week}`,
        trend: prodTrend,
        recommendation:
          prodTrend === "up"
            ? t.prodUpRec
            : prodTrend === "stable"
              ? t.prodStableRec
              : t.prodDownRec,
      },
      {
        type: "health",
        status:
          healthScore > 80 ? "good" : healthScore > 50 ? "moderate" : "poor",
        issues,
        recommendation:
          healthScore > 80
            ? t.healthGoodRec
            : healthScore > 50
              ? t.healthModRec
              : t.healthPoorRec,
      },
    ],
    actions,
  };
}
